services:
  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: file:/app/data/dev.db
    volumes:
      - backend_data:/app/data
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: /api/v1
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  backend_data:
