import type { PortfolioData } from '../types/portfolio';

export const portfolioData: PortfolioData = {
  profile: {
    id: 1,
    name: 'Mohamed Ashraf Shaaban Aata',
    headline: 'DevOps & Embedded Software Engineer',
    email: 'mohamed.ashraf13998@gmail.com',
    phone: '01112233567',
    location: 'Cairo, Egypt',
    summary:
      'DevOps & Embedded Software Engineer blending cloud-native automation with firmware fundamentals. Hands-on with AWS, Kubernetes, Terraform, Ansible, and CI/CD pipelines that emphasize reliability and measurable impact.',
    linkedin: 'https://www.linkedin.com/in/mohamed-ashraf-164749243/',
    github: 'https://github.com/MoAshraf259',
    website: null,
  },
  experiences: [
    {
      id: 1,
      role: 'DevOps Engineer',
      company: 'SEITech Solutions',
      location: 'Giza, Egypt',
      employmentType: 'Full-time',
      startDate: '2023-04-01',
      endDate: null,
      sortOrder: 1,
      highlights: [
        {
          id: 1,
          description:
            'Designed CI/CD pipelines with GitHub Actions, GitLab, and Jenkins to automate image builds and deployments.',
          sortOrder: 1,
        },
        {
          id: 2,
          description:
            'Containerized GPU-enabled LLM workloads (Ollama) with CUDA bases, smoke tests, and reproducible tagging.',
          sortOrder: 2,
        },
        {
          id: 3,
          description:
            'Implemented production-grade Flask + React CI/CD with caching, testing, image publishing, and environment-specific deploys.',
          sortOrder: 3,
        },
        {
          id: 4,
          description:
            'Automated infrastructure provisioning using Terraform and Ansible, reducing manual operations by ~60%.',
          sortOrder: 4,
        },
        {
          id: 5,
          description: 'Delivered GitOps workflows via ArgoCD for Airflow, RabbitMQ, and PostgreSQL operators.',
          sortOrder: 5,
        },
      ],
    },
    {
      id: 2,
      role: 'Embedded Software Engineer (Automotive)',
      company: 'SEITech Solutions',
      location: 'Giza, Egypt',
      employmentType: 'Full-time',
      startDate: '2021-10-01',
      endDate: '2023-03-31',
      sortOrder: 2,
      highlights: [
        {
          id: 6,
          description: 'Developed OBD-II and UDS diagnostic protocols tailored for Daimler vehicles.',
          sortOrder: 1,
        },
        {
          id: 7,
          description: 'Integrated AUTOSAR diagnostic stack using Vector tools with comprehensive CPPU unit testing.',
          sortOrder: 2,
        },
        {
          id: 8,
          description: 'Engineered real-time embedded systems leveraging simulation-driven debugging.',
          sortOrder: 3,
        },
        {
          id: 9,
          description: 'Built FlashTest & RamTest modules alongside a configurable FOTA solution for product lines.',
          sortOrder: 4,
        },
      ],
    },
    {
      id: 3,
      role: 'Mechanical Site Engineer',
      company: 'Crown Group Co.',
      location: 'Suez, Egypt',
      employmentType: 'Contract',
      startDate: '2019-06-01',
      endDate: '2020-12-31',
      sortOrder: 3,
      highlights: [
        {
          id: 10,
          description: 'Led construction of industrial thickener and conveyor systems for Suez Steel Company.',
          sortOrder: 1,
        },
        {
          id: 11,
          description: 'Coordinated cross-disciplinary teams to deliver mechanical installations on schedule.',
          sortOrder: 2,
        },
      ],
    },
  ],
  education: [
    {
      id: 1,
      institution: 'October 6 University',
      degree: 'Bachelor of Engineering',
      fieldOfStudy: 'Mechatronics / Electronics',
      location: 'Giza, Egypt',
      startDate: '2016-09-01',
      endDate: '2021-07-01',
      details: 'Graduated with a focus on embedded systems, automation, and controls.',
      sortOrder: 1,
    },
    {
      id: 2,
      institution: 'Information Technology Institute (ITI)',
      degree: 'Embedded Systems Program',
      fieldOfStudy: 'Embedded Systems',
      location: 'New Capital, Egypt',
      startDate: '2022-02-01',
      endDate: '2022-05-01',
      details: 'Intensive 3-month program covering ARM microcontrollers, RTOS, and driver development.',
      sortOrder: 2,
    },
  ],
  projects: [
    {
      id: 1,
      name: 'AI/ML Infrastructure & CI/CD (GitHub + GHCR)',
      description: 'Automated Buildx pipelines to ship GPU-accelerated Ollama images with pre-baked LLM models.',
      impact:
        'Delivered deterministic Docker image tagging, GPU availability smoke tests, and GHCR publishing for rapid experimentation.',
      type: 'DEVOPS',
      githubUrl: 'https://github.com/MoAshraf259',
      externalUrl: null,
      sortOrder: 1,
      tags: [
        { id: 1, label: 'GitHub Actions' },
        { id: 2, label: 'Docker' },
        { id: 3, label: 'CUDA' },
        { id: 4, label: 'LLM' },
        { id: 5, label: 'GHCR' },
      ],
    },
    {
      id: 2,
      name: 'Web Application CI/CD (Flask + React/Vite)',
      description: 'Designed multi-stage CI/CD for a Flask backend and React frontend with environment-aware deploys.',
      impact:
        'Enabled linting, testing, container publishing, and automated staging/production rollouts via Ansible and ArgoCD.',
      type: 'DEVOPS',
      githubUrl: 'https://github.com/MoAshraf259',
      externalUrl: null,
      sortOrder: 2,
      tags: [
        { id: 6, label: 'Flask' },
        { id: 7, label: 'React' },
        { id: 8, label: 'GitHub Actions' },
        { id: 9, label: 'ArgoCD' },
        { id: 10, label: 'Ansible' },
      ],
    },
    {
      id: 3,
      name: 'Highly Available ELK Stack Monitoring Platform',
      description:
        'Provisioned Elasticsearch cluster with Beats agents, Heartbeat checks, and secure ingress for observability.',
      impact:
        'Delivered actionable telemetry with ILM policies, APM integration, and Kibana dashboards across hybrid environments.',
      type: 'DEVOPS',
      githubUrl: 'https://github.com/MoAshraf259',
      externalUrl: null,
      sortOrder: 3,
      tags: [
        { id: 11, label: 'Elasticsearch' },
        { id: 12, label: 'Kibana' },
        { id: 13, label: 'Prometheus' },
        { id: 14, label: 'Grafana' },
        { id: 15, label: 'ILM' },
      ],
    },
    {
      id: 4,
      name: 'Automated Kubernetes Cluster Provisioning',
      description:
        'Authored Ansible playbooks to bootstrap HA Kubernetes clusters across Linux and Windows worker nodes.',
      impact: 'Implemented load-balanced control planes, ingress routing, and streamlined day-2 operations.',
      type: 'DEVOPS',
      githubUrl: 'https://github.com/MoAshraf259',
      externalUrl: null,
      sortOrder: 4,
      tags: [
        { id: 16, label: 'Kubernetes' },
        { id: 17, label: 'Ansible' },
        { id: 18, label: 'HA' },
        { id: 19, label: 'Ingress' },
        { id: 20, label: 'Automation' },
      ],
    },
    {
      id: 5,
      name: 'GitOps Integration with ArgoCD & Helm Charts',
      description:
        'Orchestrated PGO PostgreSQL operator, RabbitMQ, and Airflow deployments with custom Helm charts.',
      impact:
        'Linked GitLab CI/CD with ArgoCD for hands-free synchronization and targeted rollouts.',
      type: 'DEVOPS',
      githubUrl: 'https://github.com/MoAshraf259',
      externalUrl: null,
      sortOrder: 5,
      tags: [
        { id: 21, label: 'ArgoCD' },
        { id: 22, label: 'Helm' },
        { id: 23, label: 'GitOps' },
        { id: 24, label: 'PostgreSQL' },
        { id: 25, label: 'Airflow' },
      ],
    },
    {
      id: 6,
      name: 'Bare-metal Driver Development for STM32F4',
      description: 'Implemented SPI, I2C, and USART drivers with accompanying test applications for STM32F446.',
      impact: 'Delivered reusable peripheral drivers and documentation for rapid embedded prototyping.',
      type: 'EMBEDDED',
      githubUrl: 'https://github.com/MoAshraf259/STM32F446_MoShaaban',
      externalUrl: null,
      sortOrder: 6,
      tags: [
        { id: 26, label: 'STM32' },
        { id: 27, label: 'Embedded C' },
        { id: 28, label: 'Drivers' },
        { id: 29, label: 'SPI' },
        { id: 30, label: 'I2C' },
      ],
    },
    {
      id: 7,
      name: 'RC Car FOTA Platform',
      description: 'Built a FreeRTOS-based RC car with OTA firmware updates via dual-MCU architecture.',
      impact: 'Enabled remote firmware delivery using Wi-Fi, UART bootloading, and obstacle-avoidance controls.',
      type: 'EMBEDDED',
      githubUrl: 'https://github.com/MoAshraf259',
      externalUrl: null,
      sortOrder: 7,
      tags: [
        { id: 31, label: 'FreeRTOS' },
        { id: 32, label: 'FOTA' },
        { id: 33, label: 'STM32' },
        { id: 34, label: 'Embedded' },
        { id: 35, label: 'Automation' },
      ],
    },
  ],
  skills: [
    {
      id: 1,
      name: 'Cloud & Containers',
      sortOrder: 1,
      skills: [
        { id: 1, name: 'AWS (EC2, S3, IAM, VPC)', description: null, level: null },
        { id: 2, name: 'Docker & Containerd', description: null, level: null },
        { id: 3, name: 'Kubernetes (EKS)', description: null, level: null },
        { id: 4, name: 'Helm & Helmfile', description: null, level: null },
        { id: 5, name: 'NGINX Ingress Controller', description: null, level: null },
      ],
    },
    {
      id: 2,
      name: 'DevOps & IaC',
      sortOrder: 2,
      skills: [
        { id: 6, name: 'GitHub Actions / GitLab CI/CD / Jenkins', description: null, level: null },
        { id: 7, name: 'ArgoCD & GitOps Workflows', description: null, level: null },
        { id: 8, name: 'Terraform & Terragrunt', description: null, level: null },
        { id: 9, name: 'Ansible Automation', description: null, level: null },
        { id: 10, name: 'Systemd & NGINX deployments', description: null, level: null },
      ],
    },
    {
      id: 3,
      name: 'Observability',
      sortOrder: 3,
      skills: [
        { id: 11, name: 'ELK Stack (Elasticsearch, Kibana, Beats)', description: null, level: null },
        { id: 12, name: 'Prometheus & Grafana', description: null, level: null },
        { id: 13, name: 'Elastic APM & Heartbeat', description: null, level: null },
        { id: 14, name: 'Logging Pipelines & ILM Policies', description: null, level: null },
      ],
    },
    {
      id: 4,
      name: 'Languages',
      sortOrder: 4,
      skills: [
        { id: 15, name: 'Python', description: null, level: null },
        { id: 16, name: 'C / C++', description: null, level: null },
        { id: 17, name: 'JavaScript / Node.js', description: null, level: null },
      ],
    },
    {
      id: 5,
      name: 'Embedded Systems',
      sortOrder: 5,
      skills: [
        { id: 18, name: 'ARM Cortex-M (STM32)', description: null, level: null },
        { id: 19, name: 'FreeRTOS', description: null, level: null },
        { id: 20, name: 'Bootstrap loaders & FOTA', description: null, level: null },
        { id: 21, name: 'Diagnostics (OBD-II / UDS)', description: null, level: null },
      ],
    },
    {
      id: 6,
      name: 'Communication Protocols',
      sortOrder: 6,
      skills: [
        { id: 22, name: 'UART', description: null, level: null },
        { id: 23, name: 'SPI', description: null, level: null },
        { id: 24, name: 'I2C', description: null, level: null },
        { id: 25, name: 'CAN', description: null, level: null },
        { id: 26, name: 'Ethernet', description: null, level: null },
      ],
    },
  ],
  certifications: [
    {
      id: 1,
      name: 'Kubernetes Administrator (CKA) Preparation',
      issuer: 'KodeKloud',
      issueDate: '2024-01-01',
      credentialUrl: 'https://kodekloud.com/',
      sortOrder: 1,
    },
    {
      id: 2,
      name: 'Docker Deep Dive',
      issuer: 'KodeKloud',
      issueDate: '2023-10-01',
      credentialUrl: 'https://kodekloud.com/',
      sortOrder: 2,
    },
    {
      id: 3,
      name: 'Ultimate AWS Certified Cloud Practitioner (CLF-C02)',
      issuer: 'Udemy',
      issueDate: '2023-08-01',
      credentialUrl: 'https://www.udemy.com/',
      sortOrder: 3,
    },
  ],
  courses: [
    {
      id: 1,
      name: 'DevOps and Automation',
      provider: 'Udemy',
      link: 'https://www.udemy.com/',
      sortOrder: 1,
    },
    {
      id: 2,
      name: 'Master RTOS: Hands-on FreeRTOS and STM32Fx',
      provider: 'Udemy',
      link: 'https://www.udemy.com/',
      sortOrder: 2,
    },
    {
      id: 3,
      name: 'Mastering Microcontroller: Timers, PWM, CAN, Low Power',
      provider: 'Udemy',
      link: 'https://www.udemy.com/',
      sortOrder: 3,
    },
    {
      id: 4,
      name: 'Embedded Systems Programming on ARM Cortex-M3/M4',
      provider: 'Udemy',
      link: 'https://www.udemy.com/',
      sortOrder: 4,
    },
  ],
};
